import ts from 'typescript';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dua-auto-'));
for(const name of ['pdf-import','ocr-layout','medicine-details','auto-medicine-import','bulk-import']){let source=fs.readFileSync('lib/'+name+'.ts','utf8');for(const dependency of ['pdf-import','ocr-layout','medicine-details'])source=source.replaceAll("'./"+dependency+"'","'./"+dependency+".mjs'");fs.writeFileSync(path.join(dir,name+'.mjs'),ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);}
const {autoMedicineCSV}=await import(pathToFileURL(path.join(dir,'auto-medicine-import.mjs'))),{medicineRows}=await import(pathToFileURL(path.join(dir,'bulk-import.mjs')));
async function parse(text){const output=autoMedicineCSV(text),rows=[];for await(const row of medicineRows(new Blob([output.csv]))){assert.equal(row.error,'');rows.push(row.medicine)}return {output,rows};}
let result=await parse('Supplier list\nName\tFormula\tSelling price\tStock\tUnit\nQA A\tLabel A\tRs. 1,250.50\t12\tTablet\nQA B\tLabel B\t99\t8\tBox\nName\tFormula\tSelling price\tStock\tUnit\nQA C\tLabel C\t15\t2\tBottle\nTotal\t\t\t\t');assert.equal(result.output.count,3);assert.equal(result.rows[0].price,125050);assert.equal(result.rows[0].stock,12);assert.equal(result.rows[0].needsReview,0);
result=await parse('Medicine\tPrice\nQA incomplete\t55');assert.equal(result.output.count,1);assert.equal(result.rows[0].formula,'');assert.equal(result.rows[0].stock,0);assert.equal(result.rows[0].needsReview,1);
result=await parse('Name: QA one\nFormula: Label one\nPrice: Rs. 25\nQuantity: 10\nUnit: Tablet\nName: QA two\nFormula: Label two\nPrice: 40\nStock: 9\nUnit: Box');assert.equal(result.output.count,2);assert.equal(result.rows[1].price,4000);assert.equal(result.rows[1].stock,9);assert.equal(result.rows[0].needsReview,0);
assert.equal(autoMedicineCSV('Unknown blurry packaging\nMade for supplier').count,0);
result=await parse('Name\tFormula\tPrice\tStock\nQA wrong columns\t20\t10');assert.equal(result.rows[0].price,0);assert.equal(result.rows[0].needsReview,1);
result=await parse('Name\tFormula\tPurchase price\tMRP\tStock\tUnit\nQA costs\tLabel\t12\t15\t4\tTablet');assert.equal(result.rows[0].price,1500);assert.equal(result.rows[0].cost,1200);
const unlabelled=autoMedicineCSV('QA Example 500 mg\nQA Second product\nPrice: Rs 40','Unit',true);assert.equal(unlabelled.count,2);assert.equal(unlabelled.needsReview,2);assert.equal(autoMedicineCSV('Price: Rs 40\nStock: 10','Unit',true).count,0);
result=await parse('Name\tFormula\tPrice\tStock\tUnits per packet\nQA Tablets 500 mg\tVerified label\t10\t23\t10');assert.equal(result.rows[0].unit,'Tablet');assert.equal(result.rows[0].strength,'500 mg');assert.equal(result.rows[0].packSize,10);assert.equal(result.rows[0].needsReview,0);
const grouped=autoMedicineCSV('QA Syrup\nPrice: Rs. 50\nStock: 12\nFormula: Verified label\nUnit: Bottle\nQA Tablets\nPrice: 10\nQuantity: 30','Unit',true);const groupedRows=[];for await(const row of medicineRows(new Blob([grouped.csv])))groupedRows.push(row.medicine);assert.equal(groupedRows.length,2);assert.equal(groupedRows[0].price,5000);assert.equal(groupedRows[0].stock,12);assert.equal(groupedRows[1].price,1000);assert.equal(groupedRows[1].stock,30);assert.equal(groupedRows[0].needsReview,1);
result=await parse('Name: QA syrup\nFormula: Label\nSelling price: PKR 125.50\nStock quantity: 14\nExpiry date: 31/12/2028');assert.equal(result.rows[0].price,12550);assert.equal(result.rows[0].stock,14);assert.equal(result.rows[0].expiry,'2028-12-31');
result=await parse('Name\tFormula\tSelling price\tStock\tEXP\nQA Tablets\tLabel\t25\t8\t29-Feb-2028');assert.equal(result.rows[0].expiry,'2028-02-29');
result=await parse('Name: QA syrup\nPrice: 25\nStock: 8\nEXP: 31/02/2028');assert.equal(result.rows[0].expiry,'');assert.equal(result.rows[0].needsReview,1);
assert.equal(autoMedicineCSV("(CsTamIus A ee or mroecon pOETION (5's. {28 8 — 5 £) SH ore 400MG INF 250 ML 4973 [1063] | | = 3 Vo:",'Unit',true).count,0);
const details=await import(pathToFileURL(path.join(dir,'medicine-details.mjs')));assert.equal(details.detectMedicineDetails('QA syrup 120 ml').unit,'Bottle');assert.equal(details.detectMedicineDetails('QA cream').unit,'Tube');assert.equal(details.detectMedicineDetails('Unknown brand').unit,'Unit');assert.equal(details.adjustedStock(25,2*10),45);assert.equal(details.adjustedStock(25,-2*10),5);assert.throws(()=>details.adjustedStock(5,-10));
console.log('PASS: whole-table auto import, repeated PDF headings, multiple labelled products, prices/stock, missing details and ambiguous columns.');fs.rmSync(dir,{recursive:true});
