import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const sql=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const binding={};
binding.prepare=function(query){let args=[];const stmt={bind(...a){args=a;return stmt},async first(){return sql.prepare(query).get(...args)||null},async run(){const r=sql.prepare(query).run(...args);return {success:true,meta:{changes:Number(r.changes)},results:[]}},async all(){return {success:true,results:sql.prepare(query).all(...args),meta:{changes:0}}},query};return stmt};
binding.batch=async statements=>{sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(/^\s*SELECT/i.test(s.query)?await s.all():await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}};
globalThis.__testDB=binding;
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'dua-test-'));
function compile(src,dst){fs.writeFileSync(path.join(temp,dst),ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText)}
compile(fs.readFileSync('lib/store-server.ts','utf8').replace("import {env} from 'cloudflare:workers';","const env={DB:globalThis.__testDB};"),'server.mjs');
compile(fs.readFileSync('lib/billing.ts','utf8'),'billing.mjs');
compile(fs.readFileSync('lib/reports-server.ts','utf8').replace("'./store-server'","'./server.mjs'").replace("'./billing'","'./billing.mjs'"),'reports.mjs');
compile(fs.readFileSync('lib/catalog-server.ts','utf8').replace("'./store-server'","'./server.mjs'"),'catalog.mjs');
compile(fs.readFileSync('lib/clear-inventory.ts','utf8').replace("'./store-server'","'./server.mjs'"),'clear.mjs');
compile(fs.readFileSync('app/api/store/route.ts','utf8').replace("'@/lib/store-server'","'./server.mjs'").replace("'@/lib/catalog-server'","'./catalog.mjs'").replace("'@/lib/clear-inventory'","'./clear.mjs'").replace("'@/lib/billing'","'./billing.mjs'").replace("'@/lib/reports-server'","'./reports.mjs'"),'route.mjs');
compile(fs.readFileSync('lib/offline.ts','utf8'),'offline.mjs');
const {GET,POST}=await import(pathToFileURL(path.join(temp,'route.mjs')));
let cookie='';
const request=async(body,expected=200,authenticated=true)=>{const r=await POST(new Request('https://test.invalid/api/store',{method:'POST',headers:{'Content-Type':'application/json',...(authenticated?{cookie}:{})},body:JSON.stringify(body)}));const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return {data,r}};
assert.equal((await GET(new Request('https://test.invalid/api/store'))).status,401);
await request({action:'login',username:'admin123',password:'wrong'},401,false);
const login=await request({action:'login',username:'admin123',password:'admin'},200,false);cookie=login.r.headers.get('set-cookie').split(';')[0];
const medicine={id:'test-item',name:'QA item',formula:'Verified test label',strength:'test',manufacturer:'QA',category:'QA',barcode:'1234567890123',unit:'Unit',price:2500,cost:1500,stock:12,minimum:2,expiry:'2030-01-01',rack:'A1'};
await request({action:'save',medicine,opId:'add-1'});
await request({action:'save',medicine,opId:'add-1'});
await request({action:'save',medicine:{...medicine,id:'different'},opId:'duplicate'},409);
const snapshot=async()=>{const r=await GET(new Request('https://test.invalid/api/store',{headers:{cookie}}));assert.equal(r.status,200);return r.json()};
assert.equal((await snapshot()).medicines.length,1);
let m=(await snapshot()).medicines[0];await request({action:'save',medicine:{...m,stock:15,price:3000},opId:'edit-1'});
await request({action:'save',medicine:{...m,stock:10},opId:'stale-edit'},409);
const sale={id:'bill-1',customer:'Test customer',items:[{id:m.id,qty:4,price:3000}],paid:10000};
await request({action:'sale',sale});await request({action:'sale',sale});
let snap=await snapshot();assert.equal(snap.medicines[0].stock,11);assert.equal(snap.invoices.length,1);assert.equal(snap.invoices[0].total,12000);assert.equal(snap.summary.outstanding,2000);
await request({action:'sale',sale:{...sale,id:'too-many',items:[{id:m.id,qty:100,price:3000}]}},409);
await request({action:'sale',sale:{...sale,id:'bad-price',items:[{id:m.id,qty:1,price:1}]}},409);
await request({action:'sale',sale:{...sale,id:'bad-paid',paid:-1}},400);
const discounted={id:'discounted',customer:'Discount QA',billType:'long',items:[{id:m.id,qty:3,price:3000}],discounts:[{type:'percent',value:10},{type:'fixed',value:10}],paid:7000};
await request({action:'sale',sale:discounted});await request({action:'sale',sale:discounted});
let ds=(await snapshot()).invoices.find(x=>x.id==='discounted');assert.equal(ds.subtotal,9000);assert.equal(ds.total,7100);assert.equal(ds.discount,1900);assert.equal(ds.discounts[1].amount,1000);assert.equal(ds.billType,'long');
await request({action:'sale',sale:{...discounted,id:'invalid-discount',discounts:[{type:'percent',value:101}]}},400);
const expense={id:'expense-1',date:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Karachi'}),category:'Utilities',description:'QA expense',amount:1000};await request({action:'expense_save',expense,opId:'exp1'});await request({action:'expense_save',expense,opId:'exp1'});
const report=async(query='')=>{const r=await GET(new Request('https://test.invalid/api/store?view=reports'+query,{headers:{cookie}}));const body=await r.json();assert.equal(r.status,200,JSON.stringify(body));return body};
let financial=await report();assert.equal(financial.totals.sales,19100);assert.equal(financial.totals.discounts,1900);assert.equal(financial.totals.cost,10500);assert.equal(financial.totals.expenses,1000);assert.equal(financial.totals.netProfit,7600);assert.equal(financial.totals.outstanding,2100);assert.equal(financial.billCount,2);assert.equal((await report('&q=Discount')).billCount,1);
await request({action:'expense_save',expense:{...expense,version:1,amount:2000},opId:'exp2'});await request({action:'expense_save',expense:{...expense,version:1,amount:1},opId:'exp-stale'},409);assert.equal((await report()).totals.expenses,2000);await request({action:'expense_delete',expense:{...expense,version:2},opId:'exp-delete'});await request({action:'expense_delete',expense:{...expense,version:2},opId:'exp-delete'});assert.equal((await report()).totals.expenses,0);
const billing=await import(pathToFileURL(path.join(temp,'billing.mjs')));assert.equal(billing.billTotals(10000,[{type:'percent',value:10},{type:'percent',value:10}]).total,8100);assert.throws(()=>billing.billTotals(100,[{type:'fixed',value:2}]));
for(let i=0;i<120;i++){const rows=Array.from({length:100},(_,j)=>({...medicine,id:'bulk-'+(i*100+j),name:'Bulk '+(i*100+j),barcode:'B'+(i*100+j)}));const result=await request({action:'import',rows});assert.equal(result.data.added,100);if(i===0)assert.equal((await request({action:'import',rows})).data.added,0)}
assert.equal((await snapshot()).summary.inventory.count,12001);assert.equal((await snapshot()).medicines.length,50);
let next=null,collected=[];do {const url=next?'https://test.invalid/api/store?view=inventory&after='+encodeURIComponent(next):'https://test.invalid/api/store?view=inventory';const r=await GET(new Request(url,{headers:{cookie}}));assert.equal(r.status,200);const d=await r.json();assert.ok(d.medicines.length<=1000);collected.push(...d.medicines);next=d.next||d.medicineNext;}while(next);assert.equal(collected.length,12001);assert.equal(new Set(collected.map(m=>m.id)).size,12001);
m=sql.prepare("SELECT * FROM medicines WHERE id='test-item'").get();await request({action:'delete',medicine:m,opId:'delete-1'});await request({action:'delete',medicine:m,opId:'delete-1'});assert.equal((await snapshot()).summary.inventory.count,12000);
await request({action:'sale',sale:{...sale,id:'deleted-sale'}},409);
const addLegacy=sql.prepare("INSERT INTO invoices(id,created,customer,items,total,paid) VALUES (?, '2025-01-01T10:00:00.000Z','Legacy','[]',100,100)");for(let i=0;i<2050;i++)addLegacy.run('legacy-'+String(i).padStart(4,'0'));assert.equal((await report()).billCount,2052);assert.equal((await report('&page=42')).bills.length,2);assert.equal((await report('&from=2025-01-01&to=2025-01-01')).billCount,2050);assert.equal((await report('&q=legacy-0000')).bills[0].subtotal,100);
const {parseCSV}=await import(pathToFileURL(path.join(temp,'offline.mjs')));assert.equal(parseCSV('name,formula\n"A, B","C"\n')[0].name,'A, B');assert.throws(()=>parseCSV('name\n"broken'));
console.log('PASS: login, authorization, create/edit/delete, duplicate prevention, stale edits, 12,000-row import, repeat import, atomic bill stock deduction, bill replay, insufficient stock, price checks, balance totals, CSV parsing, two-stage discounts, expenses, profit calculations, date filters and bill pagination beyond 2,000.');
fs.rmSync(temp,{recursive:true,force:true});

const batchRows=[{...medicine,id:'resume-1',name:'Resume fixture',barcode:'resume'}];
let rb=await request({action:'import',rows:batchRows,batchId:'resume-test'});assert.equal(rb.data.added,1);
rb=await request({action:'import',rows:batchRows,batchId:'resume-test'});assert.equal(rb.data.added,1);
await request({action:'import',rows:[{...batchRows[0],price:5}],batchId:'resume-test'},409);
assert.equal((await snapshot()).summary.inventory.count,12001);
const cat=async p=>{const r=await GET(new Request('https://test.invalid/api/store?'+new URLSearchParams({view:'catalog',...p}),{headers:{cookie}}));assert.equal(r.status,200);return r.json()};
const first=await cat({});assert.equal(first.medicines.length,50);const second=await cat({after:first.next});assert.equal(second.medicines.length,50);assert.equal(new Set([...first.medicines,...second.medicines].map(m=>m.id)).size,100);
assert.equal((await cat({barcode:'resume'})).medicines[0].id,'resume-1');assert.equal((await cat({q:'resume'})).medicines[0].id,'resume-1');
const actual=sql.prepare('SELECT COUNT(*) AS count,SUM(stock<=minimum) AS low,SUM(stock=0) AS out,SUM(cost*stock) AS value FROM medicines WHERE deleted=0').get();const metric=(await snapshot()).summary.inventory;for(const key of ['count','low','out','value'])assert.equal(metric[key],actual[key]);
console.log('Bounded catalog, indexed search, exact barcode, aggregate totals and retry-safe imports passed.');
const incomplete={...medicine,id:'auto-draft',name:'Auto draft',barcode:'auto-draft',formula:'',stock:10,needsReview:1,importNotes:'Check formula.'};
await request({action:'import',rows:[incomplete],batchId:'auto-draft-import'});
assert.equal((await cat({filter:'Needs details'})).medicines[0].id,'auto-draft');
await request({action:'sale',sale:{id:'draft-sale',customer:'QA',items:[{id:'auto-draft',qty:1,price:2500}],paid:2500}},409);
await request({action:'save',medicine:{...incomplete,formula:'Verified test label',needsReview:0,importNotes:'',version:1},opId:'complete-auto-draft'});
assert.equal((await cat({filter:'Needs details'})).medicines.length,0);
await request({action:'sale',sale:{id:'draft-sale',customer:'QA',items:[{id:'auto-draft',qty:1,price:2500}],paid:2500}});
console.log('PASS: incomplete automatic imports persist, can be edited, and cannot be billed until details are completed.');

let packing=sql.prepare("SELECT * FROM medicines WHERE id='auto-draft'").get();
await request({action:'save',medicine:{...packing,stock:29,packSize:10},opId:'packet-stock-add'});
let packed=sql.prepare("SELECT * FROM medicines WHERE id='auto-draft'").get();assert.equal(packed.stock,29);assert.equal(packed.packSize,10);assert.equal(packed.price,packing.price);
await request({action:'save',medicine:{...packing,stock:19,packSize:10},opId:'stale-packet-edit'},409);
await request({action:'save',medicine:{...packed,stock:9},opId:'packet-stock-remove'});
assert.equal(sql.prepare("SELECT stock FROM medicines WHERE id='auto-draft'").get().stock,9);
await request({action:'save',medicine:{...packed,stock:-1},opId:'negative-packet-stock'},400);
console.log('PASS: packet size persists, stock additions/removals preserve price, stale and negative updates are rejected.');

const beforeBills=sql.prepare('SELECT COUNT(*) AS n FROM invoices').get().n;
await request({action:'clear_inventory',opId:'clear-test',confirm:'wrong'},400);
let removed=await request({action:'clear_inventory',opId:'clear-test',confirm:'REMOVE ALL'});assert.equal(removed.data.done,false);
await request({action:'save',medicine:{...medicine,id:'during-clear'},opId:'during-clear'},409);
while(!removed.data.done)removed=await request({action:'clear_inventory',opId:'clear-test',confirm:'REMOVE ALL'});
assert.equal((await snapshot()).summary.inventory.count,0);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM invoices').get().n,beforeBills);
await request({action:'import',rows:[medicine]},409);
await request({action:'import',rows:[medicine],catalogEpoch:'clear-test'});
await request({action:'clear_inventory',opId:'clear-test',confirm:'REMOVE ALL'});
assert.equal((await snapshot()).summary.inventory.count,1);
console.log('PASS: confirmed bulk removal, chunk/resume, preserved bills, stale-device protection, reimport and replay safety.');
await request({action:'store_profile',profile:{name:'QA Pharmacy',phone:'0300 0000000',address:'QA address',logo:''}},401,false);
await request({action:'store_profile',profile:{name:'QA Pharmacy',phone:'0300 0000000',address:'QA address',logo:''}});
assert.equal((await snapshot()).summary.storeProfile.phone,'0300 0000000');
assert.equal((await snapshot()).summary.storeProfile.name,'QA Pharmacy');
const saleItem={...medicine,qty:1};
await request({action:'sale',catalogEpoch:'clear-test',sale:{id:'expiry-print-test',customer:'QA',paid:medicine.price,items:[saleItem],discounts:[]}});
assert.equal(JSON.parse(sql.prepare('SELECT items FROM invoices WHERE id=?').get('expiry-print-test').items)[0].expiry,medicine.expiry);
console.log('PASS: authenticated store settings persist and invoice items preserve expiry.');
await request({action:'import',catalogEpoch:'clear-test',rows:[{...medicine,id:'formula-optional',name:'Formula optional',barcode:'formula-optional',unit:'Tablet',stock:5,needsReview:1,formula:''}]});
await request({action:'sale',catalogEpoch:'clear-test',sale:{id:'formula-optional-sale',customer:'QA',paid:medicine.price,items:[{id:'formula-optional',qty:1,price:medicine.price}]}});
assert.equal(sql.prepare('SELECT stock FROM medicines WHERE id=?').get('formula-optional').stock,4);
console.log('PASS: missing formula does not block a priced, identified selling unit with stock.');
