import {catalogState,clearInventory} from '@/lib/clear-inventory';
import {catalog,ensureMetrics,inventorySummary,inventoryAlerts} from '@/lib/catalog-server';
import {billTotals,decodeBill} from '@/lib/billing';
import {reports,expenseAction} from '@/lib/reports-server';
import {db,json,hash,passwordHash,authorized,clean,insert,storeProfile,cleanProfile} from '@/lib/store-server';
export async function GET(req:Request){try{if(!await authorized(req))return json({error:'Please sign in.'},401);await ensureMetrics();if(new URL(req.url).searchParams.get('view')==='catalog')return await catalog(req);if(new URL(req.url).searchParams.get('view')==='reports')return await reports(req);const params=new URL(req.url).searchParams;if(params.get('view')==='inventory'){const r=await db().prepare('SELECT * FROM medicines WHERE deleted=0 AND id>? ORDER BY id LIMIT 1000').bind(params.get('after')||'').all();return json({medicines:r.results,next:r.results.length===1000?(r.results[999] as any).id:null});}const paged=params.get('paged')==='1';const [m,i,totals,days]=await db().batch([db().prepare('SELECT * FROM medicines WHERE deleted=0 ORDER BY identity LIMIT 50'),db().prepare('SELECT * FROM invoices ORDER BY created DESC LIMIT 2000'),db().prepare('SELECT COALESCE(SUM(total-paid),0) AS outstanding FROM invoices'),db().prepare("SELECT date(created,'+5 hours') AS day, SUM(total) AS total, COUNT(*) AS count FROM invoices WHERE created>=datetime('now','-8 days') GROUP BY day")]);return json({medicines:m.results,medicineNext:paged&&m.results.length===1000?(m.results[999] as any).id:null,invoices:i.results.map(decodeBill),at:Date.now(),summary:{storeProfile:await storeProfile(),...await catalogState(),alerts:await inventoryAlerts(),inventory:await inventorySummary(),outstanding:(totals.results[0] as any)?.outstanding||0,days:days.results}});}catch(e){console.error(e);return json({error:'Unable to load shared records. Your offline data is still available.'},503);}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return json({error:'Invalid origin'},403);const b:any=await req.json();const d=db();
if(b.action==='login'){
const key=await hash(req.headers.get('cf-connecting-ip')||'shared');const now=Date.now();await d.prepare('INSERT INTO attempts (key,count,until) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END, until=CASE WHEN until<? THEN ? ELSE until END').bind(key,now+900000,now,now,now+900000).run();const limit:any=await d.prepare('SELECT count FROM attempts WHERE key=?').bind(key).first();if(limit.count>15)return json({error:'Too many attempts. Try again in 15 minutes.'},429);
const stored:any=await d.prepare("SELECT value FROM settings WHERE key='password'").first();const [salt,expected]=stored?stored.value.split(':'):['',''];const got=await passwordHash(String(b.password||''),salt);if(b.username!=='admin123'||got!==expected)return json({error:'Incorrect username or password.'},401);
const token=crypto.randomUUID()+crypto.randomUUID();await d.batch([d.prepare('INSERT INTO sessions(token,expires) VALUES (?,?)').bind(await hash(token),now+2592000000),d.prepare('DELETE FROM attempts WHERE key=?').bind(key)]);return json({ok:true},200,{'Set-Cookie':`dua_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=2592000`});}
if(!await authorized(req))return json({error:'Please sign in again to sync your changes.'},401);
if(b.action==='store_profile'){const profile=cleanProfile(b.profile);await d.prepare("INSERT INTO settings(key,value) VALUES ('store_profile',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(profile)).run();return json({ok:true,profile});}
if(b.action==='logout'){const token=req.headers.get('cookie')?.match(/dua_session=([^;]+)/)?.[1]||'';await d.prepare('DELETE FROM sessions WHERE token=?').bind(await hash(token)).run();return json({ok:true},200,{'Set-Cookie':'dua_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'});}
if(b.action==='password'){if(String(b.password||'').length<8)return json({error:'Use at least 8 characters.'},400);const salt=crypto.randomUUID();await d.batch([d.prepare("INSERT INTO settings(key,value) VALUES ('password',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(salt+':'+await passwordHash(b.password,salt)),d.prepare('DELETE FROM sessions')]);return json({ok:true});}
await ensureMetrics();
if(b.action==='expense_save'||b.action==='expense_delete')return await expenseAction(b);
if(b.action==='clear_inventory')return await clearInventory(b);
if(['import','save','delete','sale'].includes(b.action)){const current=await catalogState();if(current.clearJob)return json({error:'All-medicine removal is in progress. Resume it in Medicine stock before changing inventory.'},409);if((b.catalogEpoch||'')!==current.catalogEpoch)return json({error:'The medicine catalog was cleared on another device. Refresh and review this change before trying again.'},409);}
if(b.action==='import'){if(!Array.isArray(b.rows)||b.rows.length>100)return json({error:'Send up to 100 rows per batch.'},400);const rows=b.rows.map(clean);if(!b.batchId){const results=await d.batch(rows.map(insert));return json({added:results.reduce((n,r)=>n+Number(r.meta.changes||0),0)});}if(typeof b.batchId!=='string'||b.batchId.length>200)throw new Error('Invalid import checkpoint.');const digest=await hash(JSON.stringify(b.rows));const prior:any=await d.prepare('SELECT digest,added FROM import_batches WHERE id=?').bind(b.batchId).first();if(prior){if(prior.digest!==digest)return json({error:'The file changed. Start a new import.'},409);return json({added:prior.added});}
const fields=['id','name','formula','strength','manufacturer','category','barcode','identity','unit','price','cost','stock','minimum','expiry','rack','needsReview','importNotes','packSize'];
const results=await d.batch([d.prepare("INSERT INTO settings(key,value) SELECT ?,CAST(COALESCE(SUM(count),0) AS TEXT) FROM inventory_metrics WHERE 1 ON CONFLICT(key) DO NOTHING").bind('batch:'+b.batchId),...rows.map((m:any)=>d.prepare('INSERT INTO medicines ('+fields.join(',')+') SELECT '+fields.map(()=>'?').join(',')+' WHERE NOT EXISTS(SELECT 1 FROM import_batches WHERE id=?) ON CONFLICT DO NOTHING').bind(...fields.map(k=>m[k]),b.batchId)),d.prepare("INSERT INTO import_batches(id,digest,added,created) SELECT ?,?,COALESCE(SUM(count),0)-CAST((SELECT value FROM settings WHERE key=?) AS INTEGER),? FROM inventory_metrics WHERE 1 ON CONFLICT(id) DO NOTHING").bind(b.batchId,digest,'batch:'+b.batchId,Date.now()),d.prepare('DELETE FROM settings WHERE key=?').bind('batch:'+b.batchId)]);
const saved:any=await d.prepare('SELECT digest,added FROM import_batches WHERE id=?').bind(b.batchId).first();if(saved.digest!==digest)return json({error:'The file changed. Start a new import.'},409);return json({added:saved.added});}
if(b.action==='save'||b.action==='delete'){
if(typeof b.opId!=='string'||b.opId.length>100)return json({error:'Missing operation ID'},400);
if(await d.prepare('SELECT id FROM operations WHERE id=?').bind(b.opId).first())return json({ok:true});const m=b.action==='save'?clean(b.medicine):b.medicine;let q;
if(b.action==='delete')q=d.prepare('UPDATE medicines SET deleted=1,version=version+1 WHERE id=? AND version=? AND deleted=0').bind(m.id,m.version);
else if(!b.medicine.version)q=insert(m);else q=d.prepare('UPDATE medicines SET name=?,formula=?,strength=?,manufacturer=?,category=?,barcode=?,identity=?,unit=?,price=?,cost=?,stock=?,minimum=?,expiry=?,rack=?,needsReview=?,importNotes=?,packSize=?,version=version+1 WHERE id=? AND version=? AND deleted=0').bind(...['name','formula','strength','manufacturer','category','barcode','identity','unit','price','cost','stock','minimum','expiry','rack','needsReview','importNotes','packSize'].map(k=>m[k]),m.id,b.medicine.version);
const results=await d.batch([q,d.prepare('INSERT INTO operations(id,created) SELECT ?,? WHERE changes()>0').bind(b.opId,Date.now())]);if(!results[0].meta.changes)return json({error:'Duplicate medicine, or this record changed on another device. Review the latest stock before saving.'},409);return json({ok:true});}
if(b.action==='sale'){
const s=b.sale;if(!s||typeof s.id!=='string'||s.id.length>100||!Array.isArray(s.items)||!s.items.length||s.items.length>100)return json({error:'Bill must contain 1–100 different items.'},400);
const existing=await d.prepare('SELECT id FROM invoices WHERE id=?').bind(s.id).first();if(existing)return json({ok:true,id:s.id});
const seen=new Set();let total=0;const items=[];for(const a of s.items){if(seen.has(a.id)||!Number.isSafeInteger(a.qty)||a.qty<1||a.qty>100000)throw new Error('Invalid bill quantity.');seen.add(a.id);const m:any=await d.prepare('SELECT * FROM medicines WHERE id=? AND deleted=0').bind(a.id).first();if(m&&(m.price<=0||(m.needsReview&&m.unit==='Unit')))return json({error:'Enter the selling price and selling unit for '+m.name+' before billing.'},409);if(!m||m.price!==a.price||m.stock<a.qty||(m.expiry&&m.expiry<new Date().toISOString().slice(0,10)))return json({error:'Stock, expiry or price changed. Review the bill before completing it.'},409);items.push({id:m.id,name:m.name,unit:m.unit,formula:m.formula,strength:m.strength,qty:a.qty,price:m.price,cost:m.cost,expiry:m.expiry});total+=m.price*a.qty;}
const calculated=billTotals(total,s.discounts||[]);const subtotal=total;total=calculated.total;const created=s.created?new Date(s.created):new Date();if(!Number.isFinite(created.getTime())||created.getTime()>Date.now()+300000)throw new Error('Invalid bill date.');
if(!Number.isSafeInteger(s.paid)||s.paid<0||s.paid>total)return json({error:'Paid amount must be between zero and bill total.'},400);if(s.paid<total&&!String(s.customer||'').trim())return json({error:'Customer name is required for unpaid balance.'},400);
const guard="NOT EXISTS (SELECT 1 FROM json_each(?) j LEFT JOIN medicines m ON m.id=json_extract(j.value,'$.id') WHERE m.id IS NULL OR m.deleted!=0 OR m.price<=0 OR (m.needsReview=1 AND m.unit='Unit') OR m.stock<json_extract(j.value,'$.qty') OR m.price!=json_extract(j.value,'$.price') OR (m.expiry!='' AND m.expiry<?))";const args=[JSON.stringify(items),new Date().toISOString().slice(0,10)];
const qs=[d.prepare(`INSERT INTO invoices(id,created,customer,items,total,paid,applied,subtotal,discount,discounts,bill_type) SELECT ?,?,?,?,?,?,0,?,?,?,? WHERE ${guard} ON CONFLICT(id) DO NOTHING`).bind(s.id,created.toISOString(),String(s.customer||'Walk-in customer').slice(0,160),JSON.stringify(items),total,s.paid,subtotal,calculated.discount,JSON.stringify(calculated.discounts),s.billType==='long'?'long':'normal',...args),...items.map(x=>d.prepare('UPDATE medicines SET stock=stock-?,version=version+1 WHERE id=? AND EXISTS(SELECT 1 FROM invoices WHERE id=? AND applied=0)').bind(x.qty,x.id,s.id)),d.prepare('UPDATE invoices SET applied=1 WHERE id=?').bind(s.id)];await d.batch(qs);if(!await d.prepare('SELECT id FROM invoices WHERE id=?').bind(s.id).first())return json({error:'Stock changed during checkout. Please review this bill.'},409);return json({ok:true,id:s.id});}
return json({error:'Unknown action'},400);
}catch(e:any){console.error(e);return json({error:/UNIQUE/.test(e.message)?'A medicine with this barcode or identity already exists.':e.message||'Unable to save. Try again.'},400);}}
