export function tsvToTable(tsv:string){const words=tsv.split('\n').slice(1).map(line=>{const c=line.split('\t');return {level:Number(c[0]),x:Number(c[6]),y:Number(c[7]),w:Number(c[8]),h:Number(c[9]),text:c.slice(11).join('\t').trim()}}).filter(w=>w.level===5&&w.text&&w.w>0&&w.h>0);if(!words.length)return '';const heights=words.map(w=>w.h).sort((a,b)=>a-b),height=heights[Math.floor(heights.length/2)]||14;const lines:{y:number;words:typeof words}[]=[];for(const word of words.sort((a,b)=>a.y-b.y||a.x-b.x)){const cy=word.y+word.h/2;let line=lines.find(l=>Math.abs(l.y-cy)<height*.65);if(!line){line={y:cy,words:[]};lines.push(line)}line.words.push(word)}return lines.sort((a,b)=>a.y-b.y).map(line=>{let last=-Infinity,result='';for(const word of line.words.sort((a,b)=>a.x-b.x)){result+=(result?(word.x-last>height*1.5?'\t':' '):'')+word.text;last=word.x+word.w}return result}).join('\n')}
export function labelledMedicine(text:string){const out:Record<string,string>={name:'',formula:'',strength:'',price:'',stock:'',manufacturer:''};for(const line of text.split('\n')){const m=line.match(/^\s*(medicine(?: name)?|product(?: name)?|name|formula|generic|active ingredient|strength|selling price|sale price|retail price|price|m\.?r\.?p\.?|stock(?: quantity)?|available stock|quantity|qty|unit|selling unit|manufacturer|expiry(?: date)?|expiration(?: date)?|exp\.?|barcode)\s*[:=]\s*(.+)$/i);if(!m)continue;const label=m[1].toLowerCase();const key=/^(medicine|product|name)/.test(label)?'name':/formula|generic|ingredient/.test(label)?'formula':/price|m\.?r\.?p/.test(label)?'price':/stock|quantity|qty/.test(label)?'stock':/unit/.test(label)?'unit':/^exp/.test(label)?'expiry':label;out[key]=['price','stock'].includes(key)?m[2].replace(/^(?:PKR|Rs\.?)\s*/i,'').replaceAll(',','').trim():m[2].trim()}return out}

export function normalizeExpiry(value:string){
 const v=value.trim();let y=0,m=0,d=0;let match;
 if((match=v.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/))){y=+match[1];m=+match[2];d=+match[3];}
 else if((match=v.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{4})$/))){d=+match[1];m=+match[2];y=+match[3];}
 else if((match=v.match(/^(\d{1,2})[ -/]([A-Za-z]{3,9})[ -/](\d{4})$/))){d=+match[1];m=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].indexOf(match[2].slice(0,3).toLowerCase())+1;y=+match[3];}
 if(y<2000||y>2199||m<1||m>12||d<1||d>new Date(Date.UTC(y,m,0)).getUTCDate())return '';
 return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;
}
