export async function localDB(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('dua-offline',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function readLocal(key:string){const d=await localDB();return new Promise<any>((resolve,reject)=>{const r=d.transaction('data').objectStore('data').get(key);r.onsuccess=()=>{resolve(r.result);d.close()};r.onerror=()=>{reject(r.error);d.close()};});}
export async function writeLocal(key:string,value:any){const d=await localDB();return new Promise<void>((resolve,reject)=>{const t=d.transaction('data','readwrite');t.objectStore('data').put(value,key);t.oncomplete=()=>{d.close();resolve()};t.onerror=()=>{d.close();reject(t.error)};});}
export async function api(body?:any){const r=await fetch(body?'/api/store':'/api/store?paged=1',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok){const e:any=new Error(d.error||'Request failed');e.status=r.status;throw e}return d;}
export function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=''}else cell+=c;}if(quoted)throw new Error('Unclosed quote in CSV.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);const headers=(rows.shift()||[]).map(x=>x.trim().toLowerCase().replace(/^\uFEFF/,''));return rows.map((r)=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()])));}

export async function changeQueue(update:(queue:any[])=>any[]){const d=await localDB();return new Promise<any[]>((resolve,reject)=>{const t=d.transaction('data','readwrite');const store=t.objectStore('data');const r=store.get('queue');let result:any[]=[];r.onsuccess=()=>{try{result=update(r.result||[]);store.put(result,'queue')}catch(e){t.abort();reject(e)}};t.oncomplete=()=>{d.close();resolve(result)};t.onerror=()=>{d.close();reject(t.error)};});}

export async function catalogPage(params:Record<string,string>,signal?:AbortSignal){const r=await fetch('/api/store?'+new URLSearchParams({view:'catalog',...params}),{signal});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Unable to search inventory.');return d;}
