export function textItemsToRows(items:any[]){const lines:{y:number;items:any[]}[]=[];for(const item of items){if(typeof item.str!=='string'||!item.str.trim())continue;const y=item.transform[5],existing=lines.find(l=>Math.abs(l.y-y)<3);if(existing)existing.items.push(item);else lines.push({y,items:[item]})}return lines.sort((a,b)=>b.y-a.y).map(line=>{const sorted=line.items.sort((a,b)=>a.transform[4]-b.transform[4]);let cells:string[]=[],cell='',right=-Infinity;for(const it of sorted){const x=it.transform[4];if(cell&&x-right>12){cells.push(cell.trim());cell=''}cell+=(cell?' ':'')+it.str;right=Math.max(right,x+it.width)}if(cell)cells.push(cell.trim());return cells.join('\t')}).filter(Boolean)}
export async function extractPDF(file:File,onProgress:(s:string)=>void,workerSrc='/vendor/pdfjs-6.3.289/pdf.worker.min.mjs',signal?:AbortSignal,forceOCR=false){
 if(file.size>100*1024*1024)throw new Error('Use PDFs up to 100 MB each. Split larger files and continue importing.');
 const pdfModule='/vendor/pdfjs-6.3.289/pdf.min.mjs';const pdfjs=await import(/* webpackIgnore: true */ /* @vite-ignore */ pdfModule);pdfjs.GlobalWorkerOptions.workerSrc=workerSrc;
 const task=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),useWasm:false,standardFontDataUrl:'/pdf-fonts/',cMapUrl:'/pdf-cmaps/',cMapPacked:true});
 let ocr:Awaited<ReturnType<typeof import('./ocr')['createOCR']>>|undefined;let activeRender:any;
 const abort=()=>{activeRender?.cancel();void task.destroy()};signal?.addEventListener('abort',abort,{once:true});
 try{signal?.throwIfAborted();const doc=await task.promise;const rows:string[]=[];for(let i=1;i<=doc.numPages;i++){
 signal?.throwIfAborted();onProgress(`Reading page ${i} of ${doc.numPages}…`);const page=await doc.getPage(i),text=await page.getTextContent();let parsed=forceOCR?[]:textItemsToRows(text.items);
 if(!parsed.length){if(typeof document==='undefined')throw new Error('Scanned pages need browser text recognition.');onProgress(`Reading scanned page ${i} of ${doc.numPages}…`);const original=page.getViewport({scale:1}),scale=Math.min(2.5,2200/Math.max(original.width,original.height)),viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);activeRender=page.render({canvas,viewport});await activeRender.promise;activeRender=null;
 if(!ocr){const {createOCR}=await import('./ocr');ocr=await createOCR(m=>onProgress(`Page ${i} of ${doc.numPages} · ${m}`),signal)}
 try{const result=await ocr.read(canvas);parsed=result.text.split('\n')}catch(e:any){throw new Error(`Page ${i}: ${e.message} No medicines were saved.`)}finally{canvas.width=canvas.height=0}}
 rows.push(...parsed);page.cleanup();await new Promise(resolve=>setTimeout(resolve,0));}
 if(!rows.length)throw new Error('No readable medicine text was found.');return rows.join('\n');
 }finally{signal?.removeEventListener('abort',abort);await ocr?.close();await task.destroy()}
}
export const importFields=['ignore','name','formula','strength','manufacturer','category','barcode','unit','price','cost','stock','minimum','expiry','rack','packSize'];
export function guessField(s:string){const n=s.toLowerCase().replace(/[^a-z]/g,'');if(/^(packsize|packetsize|unitsperpack|unitsperpacket|tabletsperpacket|tabletsperpack)$/.test(n))return 'packSize';if(/^(name|medicine|medicinename|product|productname|brand)$/.test(n))return 'name';if(/formula|generic|ingredient/.test(n))return 'formula';if(/strength|dosage/.test(n))return 'strength';if(/purchase|cost/.test(n))return 'cost';if(/saleprice|sellingprice|samplerate|rate|retail|price|mrp/.test(n))return 'price';if(/stock|quantity|qty/.test(n))return 'stock';if(/manufacturer|company/.test(n))return 'manufacturer';if(/expiry|expire|expiration|^exp$|^expdate$/.test(n))return 'expiry';if(/barcode/.test(n))return 'barcode';if(/unit|form/.test(n))return 'unit';if(/category/.test(n))return 'category';if(/rack|location/.test(n))return 'rack';return 'ignore'}
export function mappedCSV(lines:string[][],mapping:string[],headers:boolean,unit:string){const active=mapping.filter(x=>x!=='ignore');if(new Set(active).size!==active.length)throw new Error('Map each field only once.');if(!['name','formula','price'].every(x=>active.includes(x)))throw new Error('Map the medicine name, formula and selling price columns.');const fields=[...active];if(!fields.includes('unit'))fields.push('unit');const escape=(s:string)=>'"'+s.replaceAll('"','""')+'"';const records=(headers?lines.slice(1):lines).filter(r=>!headers||r.join('|')!==lines[0].join('|'));const values=records.map(row=>{const record:Record<string,string>={unit};mapping.forEach((k,i)=>{if(k!=='ignore'){let value=(row[i]||'').trim();if(['price','cost'].includes(k))value=value.replace(/^(?:PKR|Rs\.?|₨)\s*/i,'').replaceAll(',','');record[k]=value}});return fields.map(k=>escape(record[k]||'')).join(',')});return fields.join(',')+'\n'+values.join('\n')}
