import {db,json} from './store-server';
import {decodeBill} from './billing';
export async function reports(req:Request){const u=new URL(req.url),p=u.searchParams;const from=p.get('from')||'',to=p.get('to')||'',q=(p.get('q')||'').slice(0,200);if([from,to].some(x=>x&&!/^\d{4}-\d{2}-\d{2}$/.test(x))||(from&&to&&from>to))return json({error:'Choose a valid date range.'},400);const page=Math.max(1,Math.min(100000,Number(p.get('page'))||1)),expensePage=Math.max(1,Math.min(100000,Number(p.get('expensePage'))||1));
const conditions=[],args:any[]=[];if(from){conditions.push('created>=?');args.push(new Date(from+'T00:00:00+05:00').toISOString())}if(to){conditions.push('created<?');args.push(new Date(Date.parse(to+'T00:00:00+05:00')+86400000).toISOString())}const where=conditions.length?' WHERE '+conditions.join(' AND '):'';
const ew=['deleted=0'],ea:any[]=[];if(from){ew.push('date>=?');ea.push(from)}if(to){ew.push('date<=?');ea.push(to)}const ewhere=' WHERE '+ew.join(' AND ');const search=q?`${where?' AND ':' WHERE '}(customer LIKE ? ESCAPE '\\' OR id LIKE ? ESCAPE '\\')`:'';const term='%'+q.replace(/[\\%_]/g,'\\$&')+'%';const sa=q?[term,term]:[];
const totals=`SELECT COUNT(*) AS count,COALESCE(SUM(total),0) AS sales,COALESCE(SUM(paid),0) AS collected,COALESCE(SUM(total-paid),0) AS outstanding,COALESCE(SUM(discount),0) AS discounts,COALESCE(SUM((SELECT SUM(COALESCE(json_extract(j.value,'$.cost'),0)*json_extract(j.value,'$.qty')) FROM json_each(invoices.items) j)),0) AS cost FROM invoices${where}`;
const group=p.get('group')==='month'?"strftime('%Y-%m',created,'+5 hours')":"date(created,'+5 hours')",egroup=p.get('group')==='month'?"substr(date,1,7)":"date";const d=db();const results=await d.batch([
d.prepare(totals).bind(...args),d.prepare(`SELECT COALESCE(SUM(amount),0) AS expenses,COUNT(*) AS count FROM expenses${ewhere}`).bind(...ea),d.prepare(`SELECT ${group} AS period,SUM(total) AS sales,SUM(discount) AS discounts,SUM(paid) AS collected FROM invoices${where} GROUP BY period ORDER BY period`).bind(...args),d.prepare(`SELECT ${egroup} AS period,SUM(amount) AS expenses FROM expenses${ewhere} GROUP BY period ORDER BY period`).bind(...ea),d.prepare(`SELECT * FROM invoices${where}${search} ORDER BY created DESC,id DESC LIMIT 50 OFFSET ?`).bind(...args,...sa,(page-1)*50),d.prepare(`SELECT COUNT(*) AS count FROM invoices${where}${search}`).bind(...args,...sa),d.prepare(`SELECT * FROM expenses${ewhere} ORDER BY date DESC,id DESC LIMIT 50 OFFSET ?`).bind(...ea,(expensePage-1)*50),d.prepare(`SELECT category,SUM(amount) AS amount FROM expenses${ewhere} GROUP BY category ORDER BY amount DESC`).bind(...ea)]);
const t:any=results[0].results[0],expense:any=results[1].results[0];return json({totals:{...t,expenses:expense.expenses,grossProfit:t.sales-t.cost,netProfit:t.sales-t.cost-expense.expenses,cashAfterExpenses:t.collected-expense.expenses},series:results[2].results,expenseSeries:results[3].results,bills:results[4].results.map(decodeBill),billCount:(results[5].results[0] as any).count,expenses:results[6].results,expenseCount:expense.count,categories:results[7].results,page,expensePage,at:Date.now()});}
export async function expenseAction(b:any){const d=db();if(typeof b.opId!=='string'||b.opId.length>100)throw new Error('Missing operation ID.');if(await d.prepare('SELECT id FROM operations WHERE id=?').bind(b.opId).first())return json({ok:true});const e=b.expense;if(!e||typeof e.id!=='string'||e.id.length>100)throw new Error('Invalid expense.');let stmt;
if(b.action==='expense_delete'){if(!Number.isSafeInteger(e.version))throw new Error('Invalid expense version.');stmt=d.prepare('UPDATE expenses SET deleted=1,version=version+1 WHERE id=? AND version=? AND deleted=0').bind(e.id,e.version)}else{if(!/^\d{4}-\d{2}-\d{2}$/.test(e.date)||!Number.isFinite(Date.parse(e.date))||!String(e.description||'').trim()||!Number.isSafeInteger(e.amount)||e.amount<=0||e.amount>100000000)throw new Error('Enter a date, description and valid amount.');const a=[e.date,String(e.category||'Other').slice(0,100),String(e.description).trim().slice(0,500),e.amount];stmt=e.version?d.prepare('UPDATE expenses SET date=?,category=?,description=?,amount=?,version=version+1 WHERE id=? AND version=? AND deleted=0').bind(...a,e.id,e.version):d.prepare('INSERT INTO expenses(id,date,category,description,amount) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(e.id,...a)}const r=await d.batch([stmt,d.prepare('INSERT INTO operations(id,created) SELECT ?,? WHERE changes()>0').bind(b.opId,Date.now())]);if(!r[0].meta.changes)return json({error:'Expense changed on another device. Refresh before editing.'},409);return json({ok:true});}
