import {env} from 'cloudflare:workers';
export const db=()=>{const binding=(env as unknown as {DB:D1Database}).DB;if(!binding)throw new Error('Storage is unavailable. Please try again.');return binding;};
export const json=(data:unknown,status=200,extra:Record<string,string>={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...extra}});
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function passwordHash(s:string,salt:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(s),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},k,256);return Array.from(new Uint8Array(b)).map(v=>v.toString(16).padStart(2,'0')).join('');}
export async function authorized(req:Request){const token=req.headers.get('cookie')?.match(/(?:^|;\s*)dua_session=([^;]+)/)?.[1];return token?!!await db().prepare('SELECT token FROM sessions WHERE token=? AND expires>?').bind(await hash(token),Date.now()).first():false;}
export const identity=(m:any)=>[m.name,m.strength,m.manufacturer,m.unit].map(x=>String(x||'').trim().toLowerCase().replace(/\s+/g,' ')).join('|');
export function clean(m:any){const x:any={};for(const k of ['id','name','formula','strength','manufacturer','category','barcode','unit','expiry','rack'])x[k]=String(m[k]??'').trim().slice(0,200);if(!x.id)x.id=crypto.randomUUID();x.needsReview=m.needsReview===1?1:0;x.importNotes=String(m.importNotes||'').slice(0,200);if(!x.name||(!x.formula&&!x.needsReview)||!x.unit)throw new Error('Name, verified formula and selling unit are required.');if(x.expiry&&(!/^\d{4}-\d{2}-\d{2}$/.test(x.expiry)||!Number.isFinite(Date.parse(x.expiry))))throw new Error('Invalid expiry date.');for(const k of ['price','cost','stock','minimum','packSize']){const n=Number(m[k]??0);if(!Number.isSafeInteger(n)||n<0||n>100000000)throw new Error('Price and quantity must be valid non-negative numbers.');x[k]=n;}x.barcode=x.barcode||null;x.identity=identity(x);return x;}
export function insert(m:any){return db().prepare('INSERT INTO medicines (id,name,formula,strength,manufacturer,category,barcode,identity,unit,price,cost,stock,minimum,expiry,rack,needsReview,importNotes,packSize) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING').bind(...['id','name','formula','strength','manufacturer','category','barcode','identity','unit','price','cost','stock','minimum','expiry','rack','needsReview','importNotes','packSize'].map(k=>m[k]));}
export async function storeProfile(){const r:any=await db().prepare("SELECT value FROM settings WHERE key='store_profile'").first();return r?JSON.parse(r.value):{name:'DUA MEDICAL STORE',owner:'',phone:'',email:'',address:'',license:'',footer:'Thank you for visiting.',logo:''};}
export function cleanProfile(raw:any){if(!raw||typeof raw!=='object')throw new Error('Enter store details.');const p:Record<string,string>={};for(const key of ['name','owner','phone','email','address','license','footer'])p[key]=String(raw[key]||'').trim().slice(0,key==='address'||key==='footer'?300:120);if(!p.name)throw new Error('Store name is required.');p.logo=String(raw.logo||'');if(p.logo.length>180000||p.logo&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(p.logo))throw new Error('Use a small PNG, JPG or WebP logo.');return p;}
