import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const medicines=sqliteTable('medicines',{id:text('id').primaryKey(),name:text('name').notNull(),formula:text('formula').notNull(),strength:text('strength').notNull(),manufacturer:text('manufacturer').notNull(),category:text('category').notNull(),barcode:text('barcode'),identity:text('identity').notNull(),unit:text('unit').notNull(),price:integer('price').notNull(),cost:integer('cost').notNull(),stock:integer('stock').notNull(),minimum:integer('minimum').notNull(),expiry:text('expiry').notNull(),rack:text('rack').notNull(),packSize:integer('packSize').notNull().default(0),needsReview:integer('needsReview').notNull().default(0),importNotes:text('importNotes').notNull().default(''),version:integer('version').notNull().default(1),deleted:integer('deleted').notNull().default(0)},t=>[uniqueIndex('medicine_identity').on(t.identity),uniqueIndex('medicine_barcode').on(t.barcode),index('medicine_review_identity').on(t.identity).where(sql`${t.deleted}=0 AND ${t.needsReview}=1`),index('medicine_active_identity').on(t.identity).where(sql`${t.deleted}=0`),index('medicine_formula_search').on(sql`lower(${t.formula})`,t.identity).where(sql`${t.deleted}=0`),index('medicine_low_identity').on(t.identity).where(sql`${t.deleted}=0 AND ${t.stock}<=${t.minimum}`),index('medicine_out_identity').on(t.identity).where(sql`${t.deleted}=0 AND ${t.stock}=0`),index('medicine_expiry_identity').on(t.expiry,t.identity).where(sql`${t.deleted}=0 AND ${t.expiry}!=''`)]);
export const invoices=sqliteTable('invoices',{id:text('id').primaryKey(),created:text('created').notNull(),customer:text('customer').notNull(),items:text('items').notNull(),total:integer('total').notNull(),paid:integer('paid').notNull(),applied:integer('applied').notNull().default(0),subtotal:integer('subtotal').notNull().default(0),discount:integer('discount').notNull().default(0),discounts:text('discounts').notNull().default('[]'),billType:text('bill_type').notNull().default('normal')},t=>[index('invoices_created').on(t.created)]);
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),expires:integer('expires').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const attempts=sqliteTable('attempts',{key:text('key').primaryKey(),count:integer('count').notNull(),until:integer('until').notNull()});
export const operations=sqliteTable('operations',{id:text('id').primaryKey(),created:integer('created').notNull()});

export const expenses=sqliteTable('expenses',{id:text('id').primaryKey(),date:text('date').notNull(),category:text('category').notNull(),description:text('description').notNull(),amount:integer('amount').notNull(),version:integer('version').notNull().default(1),deleted:integer('deleted').notNull().default(0)},t=>[index('expenses_date').on(t.date)]);

export const inventoryMetrics=sqliteTable('inventory_metrics',{expiry:text('expiry').primaryKey(),count:integer('count').notNull(),low:integer('low').notNull(),out:integer('out').notNull(),value:integer('value').notNull()});
export const importBatches=sqliteTable('import_batches',{id:text('id').primaryKey(),digest:text('digest').notNull(),added:integer('added').notNull(),created:integer('created').notNull()});
