'use client';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {Printer,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {money,decodeBill} from '@/lib/billing';
function Receipt({bill,format,profile}:{bill:any;format:string;profile:any}){const b=decodeBill(bill);const p=profile||{};return <article className={'bill-print-content '+(format==='A4'?'a4':'thermal')}><div className="print-brand"><>{p.logo?<img className="bill-store-logo" src={p.logo} alt="Store logo"/>:<Plus size={27}/>}</><div><h2>{p.name||'DUA MEDICAL STORE'}</h2>{p.address&&<p>{p.address}</p>}{p.phone&&<p>Phone: {p.phone}</p>}{p.email&&<p>{p.email}</p>}{p.owner&&<p>{p.owner}</p>}{p.license&&<p>License: {p.license}</p>}<p>{b.billType==='long'?'Long bill / detailed invoice':'Sales receipt'}</p></div></div><div className="invoice-meta"><div><b>Bill number</b><span>DUA-{b.id.slice(0,8).toUpperCase()}</span></div><div><b>Date & time</b><span>{new Date(b.created).toLocaleString('en-PK',{timeZone:'Asia/Karachi'})}</span></div><div><b>Customer</b><span>{b.customer}</span></div></div>{b.pending&&<p className="provisional-label">PROVISIONAL — PENDING SYNC</p>}<table className="invoice-lines"><thead><tr><th>Medicine</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{b.items.map((m:any)=><tr key={m.id}><td><b>{m.name} {m.strength||''}</b>{format==='A4'&&m.formula&&<small>{m.formula}</small>}<small>{m.unit}</small><small>Expiry: {m.expiry||'Not recorded'}</small></td><td>{m.qty}</td><td>{money(m.price)}</td><td>{money(m.qty*m.price)}</td></tr>)}</tbody></table><div className="invoice-summary"><div><span>Subtotal</span><b>{money(b.subtotal)}</b></div>{b.discounts.map((d:any,i:number)=><div key={i}><span>Discount {i+1}{d.type==='percent'?` (${d.value}%)`:''}</span><b>− {money(d.amount||0)}</b></div>)}{b.discounts.length===0&&<div><span>Discount</span><b>{money(b.discount||0)}</b></div>}<div className="net"><span>Net payable</span><b>{money(b.total)}</b></div><div><span>Paid</span><b>{money(b.paid)}</b></div><div><span>Remaining balance</span><b>{money(b.total-b.paid)}</b></div></div>{b.discounts.length===2&&<p className="invoice-note">Discount 2 applies after discount 1.</p>}<p className="invoice-thanks">{p.footer||'Thank you for visiting.'}</p></article>}
export default function BillReceipt({bill,onClose,profile}:{bill:any;onClose:()=>void;profile?:any}){const [format,setFormat]=useState('80 mm');useEffect(()=>{if(bill)setFormat(bill.billType==='long'||bill.bill_type==='long'?'A4':'80 mm')},[bill?.id]);return <><Dialog open={!!bill} onOpenChange={v=>!v&&onClose()}><DialogContent className={'bill-dialog '+(format==='A4'?'wide':'')}><DialogHeader><DialogTitle>Print bill</DialogTitle><DialogDescription>Print a receipt or choose “Save as PDF” in the print window.</DialogDescription></DialogHeader><div className="print-controls"><Select value={format} onValueChange={setFormat}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="80 mm">80 mm receipt</SelectItem><SelectItem value="A4">A4 detailed bill</SelectItem></SelectContent></Select><button className="primary" onClick={()=>window.print()}><Printer size={17}/>Print / save PDF</button></div>{bill&&<div className="bill-preview"><Receipt bill={bill} format={format} profile={profile}/></div>}</DialogContent></Dialog>{bill&&typeof document!=='undefined'&&createPortal(<div className="print-surface"><style>{`@media print { @page { size: ${format==='A4'?'A4':'80mm 297mm'}; margin: ${format==='A4'?'12mm':'3mm'}; } }`}</style><Receipt bill={bill} format={format} profile={profile}/></div>,document.body)}</>}
