'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {catalogPage} from '@/lib/offline';
const columns=['name','formula','strength','manufacturer','category','barcode','unit','price','cost','stock','minimum','expiry','rack','packSize'];
function line(m:any){return columns.map(k=>{let v=String(k==='price'||k==='cost'?m[k]/100:m[k]??'');if(/^[=+@-]/.test(v))v="'"+v;return '"'+v.replaceAll('"','""')+'"'}).join(',')+'\n'}
export default function CatalogExport({open,onClose,online}:{open:boolean;onClose:()=>void;online:boolean}){
 const [after,setAfter]=useState(''),[part,setPart]=useState(1),[done,setDone]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 async function run(all:boolean){setBusy(true);let writer:any;let cursor=all?'':after;try{if(all){const handle=await (window as any).showSaveFilePicker({suggestedName:'dua-medicine-stock.csv',types:[{description:'Medicine CSV',accept:{'text/csv':['.csv']}}]});writer=await handle.createWritable();await writer.write(columns.join(',')+'\n');}let text=columns.join(',')+'\n',count=0;do{const d=await catalogPage({after:cursor,export:'1'});const block=d.medicines.map(line).join('');if(writer)await writer.write(block);else text+=block;count+=d.medicines.length;cursor=d.next||'';setStatus(`${count.toLocaleString()} medicines exported…`);}while(cursor&&(all||count<10000));if(writer)await writer.close();else{const url=URL.createObjectURL(new Blob([text],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download=`dua-medicines-part-${part}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setAfter(cursor);setPart(p=>p+1);setDone(!cursor);}setStatus(`${count.toLocaleString()} medicines exported.${cursor&&!all?' Download the next part to continue.':' Complete.'}`);}catch(e:any){if(writer)await writer.abort().catch(()=>{});setStatus(e.name==='AbortError'?'Export cancelled.':e.message)}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent><DialogHeader><DialogTitle>Export medicine catalog</DialogTitle><DialogDescription>Download all saved medicine records. For a large catalog, use Save entire catalog on supported PC browsers, or download parts of up to 10,000 rows.</DialogDescription></DialogHeader>{typeof window!=='undefined'&&'showSaveFilePicker'in window&&<button className="primary" disabled={busy||!online} onClick={()=>void run(true)}>Save entire catalog</button>}<button className="secondary" disabled={busy||done||!online} onClick={()=>void run(false)}>Download part {part} (up to 10,000)</button>{done&&<button className="text-button" onClick={()=>{setAfter('');setPart(1);setDone(false);setStatus('')}}>Start another export</button>}{status&&<p role="status">{status}</p>}{!online&&<p className="error-box">Connect to export the shared catalog.</p>}<p className="hint">Keep this page open. Changes made during export may appear in later pages.</p></DialogContent></Dialog>
}
