'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {adjustedStock} from '@/lib/medicine-details';
export default function StockAdjust({medicine,onClose,onSave}:{medicine:any;onClose:()=>void;onSave:(m:any)=>Promise<void>}){
 const [stock,setStock]=useState(medicine.stock),[packSize,setPackSize]=useState(medicine.packSize||0),[amount,setAmount]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function change(direction:number,packet=false){try{if(!Number.isSafeInteger(amount)||amount<1)throw new Error('Enter a positive whole quantity.');if(packet&&(!Number.isSafeInteger(packSize)||packSize<1))throw new Error('Enter the actual units per packet first.');setStock(adjustedStock(stock,direction*amount*(packet?packSize:1)));setError('')}catch(e:any){setError(e.message)}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent><DialogHeader><DialogTitle>Adjust stock · {medicine.name}</DialogTitle><DialogDescription>Count stock in {medicine.unit.toLowerCase()}s. Packet buttons use the units per packet you enter below. Prices are unchanged.</DialogDescription></DialogHeader><div className="stock-adjust-total"><small>Stock after saving</small><strong>{stock.toLocaleString()} {medicine.unit.toLowerCase()}s</strong><small>Currently saved: {medicine.stock.toLocaleString()} · Change: {stock-medicine.stock>0?'+':''}{stock-medicine.stock}</small></div><label>Quantity to add or remove<input type="number" min="1" max="100000000" step="1" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><div className="stock-adjust-buttons"><button className="secondary" disabled={busy} onClick={()=>change(-1)}>− {amount||1} {medicine.unit.toLowerCase()}(s)</button><button className="primary" disabled={busy} onClick={()=>change(1)}>+ {amount||1} {medicine.unit.toLowerCase()}(s)</button></div>{!['Packet','Box','Strip'].includes(medicine.unit)&&<><label>{medicine.unit}s per packet<input type="number" min="0" max="100000000" step="1" value={packSize||''} placeholder="Enter the actual packet size" onChange={e=>setPackSize(Number(e.target.value))}/></label><div className="stock-adjust-buttons"><button className="secondary" disabled={busy||packSize<1} onClick={()=>change(-1,true)}>− {amount||1} packet(s)</button><button className="primary" disabled={busy||packSize<1} onClick={()=>change(1,true)}>+ {amount||1} packet(s)</button></div>{packSize>0&&<p className="hint">1 packet = {packSize} {medicine.unit.toLowerCase()}s. Total: {Math.floor(stock/packSize)} full packet(s) + {stock%packSize} loose {medicine.unit.toLowerCase()}s.</p>}</>}{error&&<p className="error-box" role="alert">{error}</p>}<div className="dialog-actions"><button className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||(stock===medicine.stock&&packSize===(medicine.packSize||0))} onClick={async()=>{setBusy(true);try{if(!Number.isSafeInteger(packSize)||packSize<0||packSize>100000000)throw new Error('Enter a valid whole packet size.');await onSave({...medicine,stock,packSize});onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{busy?'Saving…':'Save stock'}</button></div></DialogContent></Dialog>
}
