'use client';
import {useState} from 'react';
import {api} from '@/lib/offline';
const defaults={name:'DUA MEDICAL STORE',owner:'',phone:'',email:'',address:'',license:'',footer:'Thank you for visiting.',logo:''};
export default function StoreSettings({profile,online,onSaved}:{profile:any;online:boolean;onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState({...defaults,...profile}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function logo(file?:File){if(!file)return;setBusy(true);setMessage('');try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Choose a PNG, JPG or WebP up to 5 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,320/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let data=canvas.toDataURL('image/png');if(data.length>180000)data=canvas.toDataURL('image/webp',.8);if(data.length>180000)throw new Error('Choose a simpler or smaller logo.');setDraft((d:any)=>({...d,logo:data}));setMessage('Logo ready. Save store details to apply it.');}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="card settings-card store-profile-settings"><h2>Store details & logo</h2><p>Your logo appears in the app and on printed bills. Saved details sync to other devices.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{await api({action:'store_profile',profile:draft});await onSaved();setMessage('Store details saved. Open a bill to preview them.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}}><fieldset disabled={busy} style={{border:0,padding:0,margin:0}}><div className="form-grid">{[['name','Medical store name'],['owner','Owner / pharmacist'],['phone','Phone / WhatsApp number'],['email','Email'],['address','Store address'],['license','License / registration number'],['footer','Bill footer message']].map(([key,label])=><label key={key}>{label}<input required={key==='name'} type={key==='email'?'email':'text'} maxLength={key==='address'||key==='footer'?300:120} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label>Store logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{void logo(e.target.files?.[0]);e.target.value=''}}/></label></div>{draft.logo&&<div className="store-logo-preview"><img src={draft.logo} alt="Store logo preview"/><button type="button" className="secondary" onClick={()=>setDraft({...draft,logo:''})}>Remove logo</button></div>}</fieldset>{message&&<p role="status" className="hint">{message}</p>}<button className="primary" disabled={busy||!online}>{busy?'Saving…':'Save store details'}</button>{!online&&<p className="hint">Connect to update store details.</p>}</form></section>
}
